-- poc_check: sandbox/supabase-rest-client-check/ の疎通確認専用テーブル。
-- db コンテナの初回起動時（docker-entrypoint-initdb.d 経由）に自動作成される。
-- マウント方法は docker-compose.yml の db サービスを参照。
create table if not exists poc_check (
  id bigint generated by default as identity primary key,
  label text not null,
  created_at timestamptz not null default now()
);

grant usage on schema public to anon;
grant select, insert on poc_check to anon;
grant usage, select on sequence poc_check_id_seq to anon;
